2025-06-22 04:25:49,135 INFO    MainThread:63956 [wandb_setup.py:_flush():81] Current SDK version is 0.20.1
2025-06-22 04:25:49,135 INFO    MainThread:63956 [wandb_setup.py:_flush():81] Configure stats pid to 63956
2025-06-22 04:25:49,135 INFO    MainThread:63956 [wandb_setup.py:_flush():81] Loading settings from C:\Users\solos\.config\wandb\settings
2025-06-22 04:25:49,135 INFO    MainThread:63956 [wandb_setup.py:_flush():81] Loading settings from C:\Users\solos\OneDrive\Documents\College\Projects\Advanced Behavioural Analysis for Content Recommendation\Shosyn\fire_tv_neural_cde_transformer_instance_version\Shosyn-1.0\fire_tv_project\fire_tv_neural_cde_transformer\wandb\settings
2025-06-22 04:25:49,135 INFO    MainThread:63956 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-06-22 04:25:49,136 INFO    MainThread:63956 [wandb_init.py:setup_run_log_directory():703] Logging user logs to C:\Users\solos\OneDrive\Documents\College\Projects\Advanced Behavioural Analysis for Content Recommendation\Shosyn\fire_tv_neural_cde_transformer_instance_version\Shosyn-1.0\fire_tv_project\fire_tv_neural_cde_transformer\wandb\run-20250622_042549-nwly2ivh\logs\debug.log
2025-06-22 04:25:49,136 INFO    MainThread:63956 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to C:\Users\solos\OneDrive\Documents\College\Projects\Advanced Behavioural Analysis for Content Recommendation\Shosyn\fire_tv_neural_cde_transformer_instance_version\Shosyn-1.0\fire_tv_project\fire_tv_neural_cde_transformer\wandb\run-20250622_042549-nwly2ivh\logs\debug-internal.log
2025-06-22 04:25:49,136 INFO    MainThread:63956 [wandb_init.py:init():831] calling init triggers
2025-06-22 04:25:49,136 INFO    MainThread:63956 [wandb_init.py:init():836] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-06-22 04:25:49,136 INFO    MainThread:63956 [wandb_init.py:init():872] starting backend
2025-06-22 04:25:49,446 INFO    MainThread:63956 [wandb_init.py:init():875] sending inform_init request
2025-06-22 04:25:49,532 INFO    MainThread:63956 [wandb_init.py:init():883] backend started and connected
2025-06-22 04:25:49,533 INFO    MainThread:63956 [wandb_init.py:init():956] updated telemetry
2025-06-22 04:25:49,592 INFO    MainThread:63956 [wandb_init.py:init():980] communicating run to backend with 90.0 second timeout
2025-06-22 04:25:50,405 INFO    MainThread:63956 [wandb_init.py:init():1032] starting run threads in backend
2025-06-22 04:25:50,744 INFO    MainThread:63956 [wandb_run.py:_console_start():2453] atexit reg
2025-06-22 04:25:50,744 INFO    MainThread:63956 [wandb_run.py:_redirect():2301] redirect: wrap_raw
2025-06-22 04:25:50,745 INFO    MainThread:63956 [wandb_run.py:_redirect():2370] Wrapping output streams.
2025-06-22 04:25:50,745 INFO    MainThread:63956 [wandb_run.py:_redirect():2393] Redirects installed.
2025-06-22 04:25:50,749 INFO    MainThread:63956 [wandb_init.py:init():1078] run started, returning control to user process
2025-06-22 04:26:41,968 WARNING MsgRouterThr:63956 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\solos\OneDrive\Documents\College\Projects\Advanced Behavioural Analysis for Content Recommendation\Shosyn\venv\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 208, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\solos\OneDrive\Documents\College\Projects\Advanced Behavioural Analysis for Content Recommendation\Shosyn\venv\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\solos\OneDrive\Documents\College\Projects\Advanced Behavioural Analysis for Content Recommendation\Shosyn\venv\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "C:\Users\solos\OneDrive\Documents\College\Projects\Advanced Behavioural Analysis for Content Recommendation\Shosyn\venv\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 212, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\solos\OneDrive\Documents\College\Projects\Advanced Behavioural Analysis for Content Recommendation\Shosyn\venv\Lib\site-packages\wandb\sdk\interface\router.py", line 56, in message_loop
    msg = self._read_message()
  File "C:\Users\solos\OneDrive\Documents\College\Projects\Advanced Behavioural Analysis for Content Recommendation\Shosyn\venv\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-06-22 04:26:42,269 INFO    MsgRouterThr:63956 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
